dsn: ${DSN}

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - "thirty-two-(32)-character-secret-key"

session:
  cookie:
    same_site: Lax  # Change to 'None' if using HTTPS across origins
    domain: localhost
    path: /
    persistent: true  # Ensure cookie stays set beyond session
    # secure: true     # Uncomment this ONLY if you're on HTTPS

serve:
  public:
    base_url: http://localhost:4433
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:3000
      allowed_methods:
        - GET
        - POST
        - OPTIONS
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Cookie
        - Content-Type
        - Accept
        - X-Requested-With
      exposed_headers:
        - Content-Type
        - Set-Cookie
      allow_credentials: true
  admin:
    base_url: http://localhost:4434

identity:
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

selfservice:
  default_browser_return_url: http://localhost:3000/
  allowed_return_urls:
    - http://localhost:3000

  methods:
    password:
      enabled: true
    oidc:
      enabled: true
      config:
        providers:
          - id: google
            provider: google
            client_id: 446655831400-65ob6ge9d7jrf40rrkq33frf954evj68.apps.googleusercontent.com
            client_secret: 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
            mapper_url: file:///etc/config/kratos/google.jsonnet
            scope:
              - openid
              - profile
              - email

  flows:
    login:
      ui_url: http://localhost:3000/login
      after:
        oidc:
          default_browser_return_url: http://localhost:3000/  
    registration:
      ui_url: http://localhost:3000/register
      after:
        password:
          default_browser_return_url: http://localhost:3000/
        oidc:
          default_browser_return_url: http://localhost:3000/
    logout:
      after:
        default_browser_return_url: http://localhost:3000/
    error:
      ui_url: http://localhost:3000/error

hashers:
  argon2:
    parallelism: 1
    memory: 512MB
    iterations: 2
    salt_length: 16
    key_length: 16

courier:
  smtp:
    connection_uri: smtps://stub:stub@stub.stub:465
